part4: add draft solution
spanish-inquisition-optimization/GradientDescent pull request #10
Opened 2023-03-27 18:17 UTC by Potato-h

Awaiting for review

2023-03-27 19:48 UTC, donRumata03 requested changes

2023-03-27 19:48 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +        visualize_optimizing_process(f, roi, np.array(gradient_descent(f, df, x0, linear_search, lambda f, points: len(points) > 20)))
Может быть, выводить также логарифмическое поведение ошибки для наглядности (передавать `0` последним аргументом `visualize_optimizing_process` — так как константу не добавляем → у этих квадратичных минимум просто ноль)

2023-03-27 19:48 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +        print(f"Optimizing with fixed step = {step}:")
Гораздо нагляднее видеть эту надпись над каждым блоком графиков, а не в консоли. Поэтому предлагаю
1) Зачеррипикать #11

2023-03-27 19:48 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +        visualize_optimizing_process(f, roi, np.array(gradient_descent(f, df, x0, linear_search, lambda f, points: len(points) > 20)))
2. `return visualize_optimizing_process(…)`

2023-03-27 19:48 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +        visualize_optimizer_with(fixed_step_search(step))
3. `visualize_optimizer_with(fixed_step_search(step)).suptitle(f"Optimizing with fixed step = {step}:", fontsize=14)`

2023-03-27 19:48 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +def create_quadratic(a, b, c, d, e):
Базироваться на `optimizer_evaluator.QuadraticForm` для минимизации сложности, повторений и ошибок не хочешь?

2023-03-27 19:48 UTC, donRumata03 commented on part_4.ipynb
Круто, очень подробный качественный анализ на самых экстремальных примерах…

Ещё бы
- сравнить (количественно, не качественно) скорость сходимости для двух разных чисел обусловленности (именно наглядно (не как в 6-м пункте), чтобы была траектория, зигзаги и было видно, что при малом числе зигзаги небольшие и сразу идут в цель, а при большом — не сразу)
- Показать примере и на графике (+ наверное, в теорОбосновании) инвариантность относительно добавление линейной компоненты (там же, по идее, выделяются полные квадраты → просто смещяется всё и зависимость, опять же, только от матрицы квадратичной формы)

2023-03-27 19:51 UTC, Potato-h commented on core/quadratic_analyzer.py
> +        visualize_optimizing_process(f, roi, np.array(gradient_descent(f, df, x0, linear_search, lambda f, points: len(points) > 20)))
Выводить ошибки стоит, но минимум там будет [не всегда](https://www.wolframalpha.com/input?i=x%5E2+%2B2+xy+%2B+2y%5E2+%2B+4x) 0

2023-03-27 20:16 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +        visualize_optimizing_process(f, roi, np.array(gradient_descent(f, df, x0, linear_search, lambda f, points: len(points) > 20)))
Да, действаительно, там же ещё линейная составляющая…
В общем, тогда, если не влом, можешь посчитать настоящий минимум, например, бесконечными итерациями (как я делал в part 1), либа аналитическим решением

А если функция бесконечно убывает, нужно тоже что-то красивое как-то вывести…

2023-04-03 23:41 UTC, Potato-h commented on core/quadratic_analyzer.py
> +        visualize_optimizer_with(fixed_step_search(step))
fix

2023-04-03 23:41 UTC, Potato-h commented on core/quadratic_analyzer.py
> +        visualize_optimizing_process(f, roi, np.array(gradient_descent(f, df, x0, linear_search, lambda f, points: len(points) > 20)))
fix

2023-04-03 23:41 UTC, Potato-h commented on core/quadratic_analyzer.py
> +        print(f"Optimizing with fixed step = {step}:")
fix

2023-04-03 23:43 UTC, Potato-h commented on core/quadratic_analyzer.py
> +def create_quadratic(a, b, c, d, e):
В некоторых случаях нужна линейная часть

2023-04-03 23:43 UTC, Potato-h commented on part_4.ipynb
кажется, сделал

2023-04-04 19:12 UTC, merged

2023-04-04 19:12 UTC, donRumata03 commented
Масштабно… Не завидую проверяющему — у него, наверное, крыша поедет от такого количество графиков…

2023-04-04 19:14 UTC, donRumata03 commented on core/quadratic_analyzer.py
> +def create_quadratic(a, b, c, d, e):
Ну, можно было бы её добавить (и, кстати, красиво находить минимум или отсутствие, как решение линейного уравнения, но ладно…